### ISSUE TITLE
Check why some RSS feeds are not working

### ISSUE THREAD

**Issue by ktjln** [ktjln/Inky-Calendar#3]
E.g. Tagesschau or Guardian

**Comment by aceisace** [comment]
@ktjln Just adding a bit of info here to help you with debugging:
* the library used to parse rss-feeds is feedparser
* currently, any RSS-feeds containing images, too long summaries, or unsupported RSS-formats cannot be shown correctly
* Current limitation: any rss-feeds that are too long to fully fit in the allocated space (multiple-lines), are not shown at all. 

Hope this helps :)

**Comment by sjstrobl** [comment]
see commit 729b48677ce88201865a32fd3d913879295a6d38
